BUNDLE_PATH = ENV.fetch('BUNDLE_PATH') { File.expand_path('../vendor/bundle', __dir__) }
source "https://rubygems.org"

gem "rails", "~> 7.2.1"
ruby '3.1.2'
gem "pg", "~> 1.1"
gem "puma", ">= 5.0"
gem "tzinfo-data", platforms: %i[mswin mingw x64_mingw jruby]
gem "bootsnap", require: false

# Use Rack CORS for handling Cross-Origin Resource Sharing (CORS), making cross-origin Ajax possible
gem "rack-cors"

group :development, :test do
  gem "debug", platforms: %i[mri mswin mingw x64_mingw], require: "debug/prelude"
  gem "brakeman", require: false
  gem "rubocop-rails-omakase", require: false
end